[font]
# default: family = "monospace", size = 11.25
normal = { family = "Fira Code", style = "Regular" }
size = 13.0

[colors]
primary.foreground = "#d8d8d8"
primary.background = "#181818"
cursor = { text = "CellBackground", cursor = "CellForeground" }
vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }

[colors.search]
matches = { foreground = "#181818", background = "#ac4242" }
focused_match = { foreground = "#181818", background = "#f4bf75" }

[colors.hints]
start = { foreground = "#181818", background = "#f4bf75" }
end = { foreground = "#181818", background = "#ac4242" }
line_indicator = { foreground = "None", background = "None" }
footer_bar = { foreground = "#181818", background = "#d8d8d8" }
selection = { text = "CellBackground", background = "CellForeground" }

[colors.normal]
black = "#181818"
red = "#ac4242"
green = "#90a959"
yellow = "#f4bf75"
blue = "#6a9fb5"
magenta = "#aa759f"
cyan = "#75b5aa"
white = "#d8d8d8"

[colors.bright]
black = "#6b6b6b"
red = "#c55555"
green = "#aac474"
yellow = "#feca88"
blue = "#82b8c8"
magenta = "#c28cb8"
cyan = "#93d3c3"
white = "#f8f8f8"

[colors.dim]
black = "#0f0f0f"
red = "#712b2b"
green = "#5f6f3a"
yellow = "#a17e4d"
blue = "#456877"
magenta = "#704d68"
cyan = "#4d7770"
white = "#8e8e8e"
indexed_colors = []
transparent_background_colors = false
draw_bold_text_with_bright_colors = false

[bell]
animation = "Linear"
duration = 0
color = "#ffffff"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "Off" }
vi_mode_style = "None"
blink_interval = 750
unfocused_hollow = true
thickness = 0.15

[terminal]
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = false
bindings = []

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[keyboard]
bindings = []

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
renderer = "None"
print_events = false
highlight_damage = false
prefer_egl = false
