[manager]
prepend_keymap = [
  { on = [ "<Enter>" ], run = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },
  { on = [ "l" ], run = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },
  { on = [ "p" ], run = "plugin --sync smart-paste", desc = "Paste into the hovered directory or CWD" },
]

[input]
prepend_keymap = [
  { on = [ "<Esc>" ], run = "close", desc = "Cancel input" },
]
